services:
  app:
    image: ${HARBOR_DOMAIN_NAME}/model-serving/chest_ct_ner:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - 9528:9528
